name: virtuhand
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.24
  - opencv>=4.9
  - tensorflow>=2.13
  - mediapipe>=0.10
  - pyrealsense2>=2.55
  - websockets>=13.1
  - onnx>=1.12
  - onnxruntime>=1.12
  - pytorch>=2.1
  - cudatoolkit=11.2
  - cudnn=8.9
  - matplotlib>=3.7
  - scipy>=1.10
  - pandas>=1.5
  - scikit-learn>=1.0
  - jupyter
  - ipykernel
  - pip:
    - tf2onnx>=1.16
    - onnx-simplifier>=0.4
    - tensorboard>=2.13
    - opencv-contrib-python>=4.10
    - rich>=13.9  
    - tqdm>=4.67  